// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_LABELHEADER 1
#define UI_COMP_HEADER_HOMEBUTTON 2
#define UI_COMP_HEADER_HOMEBUTTON_HOMEICON 3
#define _UI_COMP_HEADER_NUM 4
lv_obj_t * ui_Header_create(lv_obj_t * comp_parent);
void ui_event_comp_Header_homeButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
