// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_AUDIOSCREEN_H
#define UI_AUDIOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_audioScreen
extern void ui_audioScreen_screen_init(void);
extern void ui_audioScreen_screen_destroy(void);
extern void ui_event_audioScreen(lv_event_t * e);
extern lv_obj_t * ui_audioScreen;
extern lv_obj_t * ui_Header4;
extern lv_obj_t * ui_bodyAudio;
extern lv_obj_t * ui_micContainer;
extern lv_obj_t * ui_micContainerLabel;
extern lv_obj_t * ui_micLed;
extern void ui_event_recordMicBtn(lv_event_t * e);
extern lv_obj_t * ui_recordMicBtn;
extern lv_obj_t * ui_recordmicBtnLabel;
extern lv_obj_t * ui_outAudioContainer;
extern lv_obj_t * ui_outAudioContainerLabel;
extern lv_obj_t * ui_outAudioLed;
extern lv_obj_t * ui_volumeContainer;
extern lv_obj_t * ui_volumeLabel;
extern void ui_event_volumeSlider(lv_event_t * e);
extern lv_obj_t * ui_volumeSlider;
extern lv_obj_t * ui_outAudioBtnCtn;
extern void ui_event_selectFileAudioBtn(lv_event_t * e);
extern lv_obj_t * ui_selectFileAudioBtn;
extern lv_obj_t * ui_selectFileAudioBtnLabel;
extern void ui_event_playStopAudioBtn(lv_event_t * e);
extern lv_obj_t * ui_playStopAudioBtn;
extern lv_obj_t * ui_playStopAudioBtnLabel;
extern void ui_event_resetAudioBtn(lv_event_t * e);
extern lv_obj_t * ui_resetAudioBtn;
extern lv_obj_t * ui_resetAudioBtnLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

