// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_BUZZERSCREEN_H
#define UI_BUZZERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_buzzerScreen
extern void ui_buzzerScreen_screen_init(void);
extern void ui_buzzerScreen_screen_destroy(void);
extern void ui_event_buzzerScreen(lv_event_t * e);
extern lv_obj_t * ui_buzzerScreen;
extern lv_obj_t * ui_headerBuzzerScreen;
extern lv_obj_t * ui_buzzerBodyCtn;
extern lv_obj_t * ui_titleBuzzer;
extern void ui_event_buzzerBtn(lv_event_t * e);
extern lv_obj_t * ui_buzzerBtn;
extern lv_obj_t * ui_descriptionBuzzerCtn;
extern lv_obj_t * ui_descriptionBuzzerLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

