// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "../ui.h"

lv_obj_t * ui_buzzerScreen = NULL;
lv_obj_t * ui_headerBuzzerScreen = NULL;
lv_obj_t * ui_buzzerBodyCtn = NULL;
lv_obj_t * ui_titleBuzzer = NULL;
lv_obj_t * ui_buzzerBtn = NULL;
lv_obj_t * ui_descriptionBuzzerCtn = NULL;
lv_obj_t * ui_descriptionBuzzerLabel = NULL;
// event funtions
void ui_event_buzzerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_cameraScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_cameraScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_audioScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_audioScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initBuzzerScreen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        deinitBuzzerScreen(e);
    }
}

void ui_event_buzzerBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnBuzzerClkHandler(e);
    }
}

// build funtions

void ui_buzzerScreen_screen_init(void)
{
    ui_buzzerScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_buzzerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_buzzerScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_buzzerScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_buzzerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BACKGROUND);
    ui_object_set_themeable_style_property(ui_buzzerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BACKGROUND);
    lv_obj_set_style_pad_left(ui_buzzerScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_buzzerScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_buzzerScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_buzzerScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_buzzerScreen, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_buzzerScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerBuzzerScreen = ui_Header_create(ui_buzzerScreen);
    lv_obj_set_x(ui_headerBuzzerScreen, 0);
    lv_obj_set_y(ui_headerBuzzerScreen, -1);

    ui_buzzerBodyCtn = lv_obj_create(ui_buzzerScreen);
    lv_obj_set_width(ui_buzzerBodyCtn, lv_pct(70));
    lv_obj_set_height(ui_buzzerBodyCtn, lv_pct(70));
    lv_obj_set_align(ui_buzzerBodyCtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_buzzerBodyCtn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_buzzerBodyCtn, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_buzzerBodyCtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buzzerBodyCtn, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buzzerBodyCtn, lv_color_hex(0xFDF3E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buzzerBodyCtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buzzerBodyCtn, lv_color_hex(0xB8580A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buzzerBodyCtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buzzerBodyCtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_buzzerBodyCtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buzzerBodyCtn, lv_color_hex(0xA0A0A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buzzerBodyCtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_buzzerBodyCtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_buzzerBodyCtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buzzerBodyCtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buzzerBodyCtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleBuzzer = lv_label_create(ui_buzzerBodyCtn);
    lv_obj_set_width(ui_titleBuzzer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titleBuzzer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_titleBuzzer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titleBuzzer, "BUZZER");
    lv_obj_set_style_text_color(ui_titleBuzzer, lv_color_hex(0xB8580A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titleBuzzer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titleBuzzer, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_titleBuzzer, lv_color_hex(0xB8580A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_titleBuzzer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_titleBuzzer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_titleBuzzer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buzzerBtn = lv_button_create(ui_buzzerBodyCtn);
    lv_obj_set_width(ui_buzzerBtn, 120);
    lv_obj_set_height(ui_buzzerBtn, 120);
    lv_obj_set_x(ui_buzzerBtn, 19);
    lv_obj_set_y(ui_buzzerBtn, 1);
    lv_obj_set_align(ui_buzzerBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buzzerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buzzerBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buzzerBtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buzzerBtn, lv_color_hex(0x34C759), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buzzerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_buzzerBtn, &ui_img_bell_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buzzerBtn, lv_color_hex(0x1E8A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buzzerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buzzerBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_buzzerBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buzzerBtn, lv_color_hex(0x1A6B2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buzzerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_buzzerBtn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_buzzerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buzzerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buzzerBtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_buzzerBtn, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_buzzerBtn, lv_color_hex(0xFF3B30), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_buzzerBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_buzzerBtn, &ui_img_ringing_bell_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_buzzerBtn, lv_color_hex(0xCC1A0F), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_buzzerBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_buzzerBtn, 2, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_buzzerBtn, lv_color_hex(0x99140A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_buzzerBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_buzzerBtn, 6, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_buzzerBtn, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_buzzerBtn, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_buzzerBtn, 4, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_descriptionBuzzerCtn = lv_obj_create(ui_buzzerBodyCtn);
    lv_obj_set_width(ui_descriptionBuzzerCtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_descriptionBuzzerCtn, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_descriptionBuzzerCtn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_descriptionBuzzerCtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_descriptionBuzzerCtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_descriptionBuzzerCtn, lv_color_hex(0xB8580A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_descriptionBuzzerCtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_descriptionBuzzerCtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_descriptionBuzzerCtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_descriptionBuzzerCtn, lv_color_hex(0xA0A0A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_descriptionBuzzerCtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_descriptionBuzzerCtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_descriptionBuzzerCtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_descriptionBuzzerCtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_descriptionBuzzerCtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_descriptionBuzzerLabel = lv_label_create(ui_descriptionBuzzerCtn);
    lv_obj_set_width(ui_descriptionBuzzerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_descriptionBuzzerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_descriptionBuzzerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_descriptionBuzzerLabel, "Premi i pulsanti fisici per cambiare il tono del buzzer");

    lv_obj_add_event_cb(ui_buzzerBtn, ui_event_buzzerBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buzzerScreen, ui_event_buzzerScreen, LV_EVENT_ALL, NULL);

}

void ui_buzzerScreen_screen_destroy(void)
{
    if(ui_buzzerScreen) lv_obj_del(ui_buzzerScreen);

    // NULL screen variables
    ui_buzzerScreen = NULL;
    ui_headerBuzzerScreen = NULL;
    ui_buzzerBodyCtn = NULL;
    ui_titleBuzzer = NULL;
    ui_buzzerBtn = NULL;
    ui_descriptionBuzzerCtn = NULL;
    ui_descriptionBuzzerLabel = NULL;

}
