// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "../ui.h"

lv_obj_t * ui_buzzerScreen = NULL;
lv_obj_t * ui_Header2 = NULL;
lv_obj_t * ui_titleBuzzerLabel = NULL;
lv_obj_t * ui_buzzerBtn = NULL;
lv_obj_t * ui_buzzerBtnLabel = NULL;
// event funtions
void ui_event_buzzerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_audioScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_audioScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_cameraScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_cameraScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initBuzzerScreen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        deinitBuzzerScreen(e);
    }
}

void ui_event_buzzerBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnBuzzerClkHandler(e);
    }
}

// build funtions

void ui_buzzerScreen_screen_init(void)
{
    ui_buzzerScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_buzzerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_buzzerScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_buzzerScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_buzzerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BACKGROUND);
    ui_object_set_themeable_style_property(ui_buzzerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BACKGROUND);

    ui_Header2 = ui_Header_create(ui_buzzerScreen);
    lv_obj_set_x(ui_Header2, 0);
    lv_obj_set_y(ui_Header2, -1);

    ui_titleBuzzerLabel = lv_label_create(ui_buzzerScreen);
    lv_obj_set_height(ui_titleBuzzerLabel, lv_pct(33));
    lv_obj_set_width(ui_titleBuzzerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_titleBuzzerLabel, 3);
    lv_obj_set_y(ui_titleBuzzerLabel, -124);
    lv_obj_set_align(ui_titleBuzzerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titleBuzzerLabel, "\n\n\nUSA I PULSANTI LATERALI PER CAMBIARE IL TONO");
    ui_object_set_themeable_style_property(ui_titleBuzzerLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_titleBuzzerLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_decor(ui_titleBuzzerLabel, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titleBuzzerLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buzzerBtn = lv_button_create(ui_buzzerScreen);
    lv_obj_set_width(ui_buzzerBtn, lv_pct(30));
    lv_obj_set_height(ui_buzzerBtn, lv_pct(10));
    lv_obj_set_x(ui_buzzerBtn, 19);
    lv_obj_set_y(ui_buzzerBtn, 1);
    lv_obj_set_align(ui_buzzerBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buzzerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buzzerBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buzzerBtn, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buzzerBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buzzerBtnLabel = lv_label_create(ui_buzzerBtn);
    lv_obj_set_width(ui_buzzerBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_buzzerBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_buzzerBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_buzzerBtnLabel, "ACCENDI IL BUZZER");
    ui_object_set_themeable_style_property(ui_buzzerBtnLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_buzzerBtnLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_buzzerBtnLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buzzerBtn, ui_event_buzzerBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buzzerScreen, ui_event_buzzerScreen, LV_EVENT_ALL, NULL);

}

void ui_buzzerScreen_screen_destroy(void)
{
    if(ui_buzzerScreen) lv_obj_del(ui_buzzerScreen);

    // NULL screen variables
    ui_buzzerScreen = NULL;
    ui_Header2 = NULL;
    ui_titleBuzzerLabel = NULL;
    ui_buzzerBtn = NULL;
    ui_buzzerBtnLabel = NULL;

}
