// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_CONNECTIVITYSCREEN_H
#define UI_CONNECTIVITYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_connectivityScreen
extern void ui_connectivityScreen_screen_init(void);
extern void ui_connectivityScreen_screen_destroy(void);
extern void ui_event_connectivityScreen(lv_event_t * e);
extern lv_obj_t * ui_connectivityScreen;
extern lv_obj_t * ui_headerConnectivityScreen;
extern lv_obj_t * ui_connectivityBody;
extern lv_obj_t * ui_connectivityList;
extern lv_obj_t * ui_connectivitySelectorCtn;
extern void ui_event_wifiBtn(lv_event_t * e);
extern lv_obj_t * ui_wifiBtn;
extern lv_obj_t * ui_wifiBtnLabel;
extern void ui_event_bthBtn(lv_event_t * e);
extern lv_obj_t * ui_bthBtn;
extern lv_obj_t * ui_bthBtnLabel;
extern void ui_event_scanNetButton(lv_event_t * e);
extern lv_obj_t * ui_scanNetButton;
extern lv_obj_t * ui_labelNetButton;
extern lv_obj_t * ui_connectivityBtnContainer;
extern lv_obj_t * ui_connectivityAccess;
extern lv_obj_t * ui_logConnectivityArea;
extern lv_obj_t * ui_accessConnectivityCtn;
extern lv_obj_t * ui_passwordFieldConnectivity;
extern void ui_event_connectBtn(lv_event_t * e);
extern lv_obj_t * ui_connectBtn;
extern lv_obj_t * ui_labelConnectBtn;
extern lv_obj_t * ui_KeyboardConnectivity;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

