// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "../ui.h"

lv_obj_t * ui_connectivityScreen = NULL;
lv_obj_t * ui_Header1 = NULL;
lv_obj_t * ui_connectivityBody = NULL;
lv_obj_t * ui_connectivityList = NULL;
lv_obj_t * ui_connectivitySelectorCtn = NULL;
lv_obj_t * ui_wifiBtn = NULL;
lv_obj_t * ui_wifiBtnLabel = NULL;
lv_obj_t * ui_bthBtn = NULL;
lv_obj_t * ui_bthBtnLabel = NULL;
lv_obj_t * ui_divisorLine = NULL;
lv_obj_t * ui_scanNetButton = NULL;
lv_obj_t * ui_labelNetButton = NULL;
lv_obj_t * ui_connectivityBtnContainer = NULL;
lv_obj_t * ui_connectivityAccess = NULL;
lv_obj_t * ui_logConnectivityArea = NULL;
lv_obj_t * ui_accessConnectivityCtn = NULL;
lv_obj_t * ui_passwordFieldConnectivity = NULL;
lv_obj_t * ui_connectBtn = NULL;
lv_obj_t * ui_labelConnectBtn = NULL;
lv_obj_t * ui_KeyboardConnectivity = NULL;
// event funtions
void ui_event_connectivityScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initConnectivityScreen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        deinitConnectivityScreen(e);
    }
}

void ui_event_wifiBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deinitWifiMode(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        initWifiMode(e);
    }
}

void ui_event_bthBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        initBthMode(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deinitBthMode(e);
    }
}

void ui_event_scanNetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardConnectivity, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_accessConnectivityCtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        scanNetwork(e);
    }
}

void ui_event_connectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectDisconnectSelected(e);
    }
}

// build funtions

void ui_connectivityScreen_screen_init(void)
{
    ui_connectivityScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_connectivityScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_connectivityScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BACKGROUND);
    ui_object_set_themeable_style_property(ui_connectivityScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BACKGROUND);

    ui_Header1 = ui_Header_create(ui_connectivityScreen);
    lv_obj_set_x(ui_Header1, 0);
    lv_obj_set_y(ui_Header1, -1);

    ui_connectivityBody = lv_obj_create(ui_connectivityScreen);
    lv_obj_remove_style_all(ui_connectivityBody);
    lv_obj_set_width(ui_connectivityBody, lv_pct(100));
    lv_obj_set_height(ui_connectivityBody, lv_pct(88));
    lv_obj_set_align(ui_connectivityBody, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_connectivityBody, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_connectivityBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_connectivityBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_connectivityBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_connectivityBody, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectivityList = lv_obj_create(ui_connectivityBody);
    lv_obj_remove_style_all(ui_connectivityList);
    lv_obj_set_width(ui_connectivityList, lv_pct(69));
    lv_obj_set_height(ui_connectivityList, lv_pct(100));
    lv_obj_set_x(ui_connectivityList, -155);
    lv_obj_set_y(ui_connectivityList, -76);
    lv_obj_set_align(ui_connectivityList, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_connectivityList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_connectivityList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_connectivityList, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_connectivityList, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_connectivityList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectivitySelectorCtn = lv_obj_create(ui_connectivityList);
    lv_obj_remove_style_all(ui_connectivitySelectorCtn);
    lv_obj_set_width(ui_connectivitySelectorCtn, lv_pct(100));
    lv_obj_set_height(ui_connectivitySelectorCtn, lv_pct(11));
    lv_obj_set_align(ui_connectivitySelectorCtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connectivitySelectorCtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_connectivitySelectorCtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_connectivitySelectorCtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_connectivitySelectorCtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_connectivitySelectorCtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBtn = lv_button_create(ui_connectivitySelectorCtn);
    lv_obj_set_width(ui_wifiBtn, lv_pct(30));
    lv_obj_set_height(ui_wifiBtn, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_wifiBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_wifiBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_wifiBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BTN);
    ui_object_set_themeable_style_property(ui_wifiBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BTN);

    ui_wifiBtnLabel = lv_label_create(ui_wifiBtn);
    lv_obj_set_width(ui_wifiBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiBtnLabel, "WiFi");
    lv_obj_set_style_text_font(ui_wifiBtnLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bthBtn = lv_button_create(ui_connectivitySelectorCtn);
    lv_obj_set_width(ui_bthBtn, lv_pct(30));
    lv_obj_set_height(ui_bthBtn, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_bthBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bthBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_bthBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_bthBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BTN);
    ui_object_set_themeable_style_property(ui_bthBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BTN);

    ui_bthBtnLabel = lv_label_create(ui_bthBtn);
    lv_obj_set_width(ui_bthBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bthBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bthBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bthBtnLabel, "Bluetooth");
    lv_obj_set_style_text_font(ui_bthBtnLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_divisorLine = lv_obj_create(ui_connectivityList);
    lv_obj_set_width(ui_divisorLine, lv_pct(100));
    lv_obj_set_height(ui_divisorLine, lv_pct(1));
    lv_obj_set_align(ui_divisorLine, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_divisorLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scanNetButton = lv_button_create(ui_connectivityList);
    lv_obj_set_height(ui_scanNetButton, 50);
    lv_obj_set_width(ui_scanNetButton, lv_pct(90));
    lv_obj_set_align(ui_scanNetButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_scanNetButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_scanNetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_scanNetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scanNetButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scanNetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_scanNetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_scanNetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_border_width(ui_scanNetButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_scanNetButton, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelNetButton = lv_label_create(ui_scanNetButton);
    lv_obj_set_width(ui_labelNetButton, lv_pct(100));
    lv_obj_set_height(ui_labelNetButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelNetButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelNetButton, "RICERCA RETI O DISPOSITIVI DISPONIBILI");
    ui_object_set_themeable_style_property(ui_labelNetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_labelNetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_align(ui_labelNetButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelNetButton, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_labelNetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_labelNetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_border_width(ui_labelNetButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_labelNetButton, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelNetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelNetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelNetButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelNetButton, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectivityBtnContainer = lv_obj_create(ui_connectivityList);
    lv_obj_remove_style_all(ui_connectivityBtnContainer);
    lv_obj_set_width(ui_connectivityBtnContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_connectivityBtnContainer, 1);
    lv_obj_set_x(ui_connectivityBtnContainer, 68);
    lv_obj_set_y(ui_connectivityBtnContainer, -462);
    lv_obj_set_align(ui_connectivityBtnContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connectivityBtnContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_connectivityBtnContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_connectivityBtnContainer, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_connectivityBtnContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_connectivityBtnContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectivityAccess = lv_obj_create(ui_connectivityBody);
    lv_obj_remove_style_all(ui_connectivityAccess);
    lv_obj_set_width(ui_connectivityAccess, lv_pct(30));
    lv_obj_set_height(ui_connectivityAccess, lv_pct(100));
    lv_obj_set_x(ui_connectivityAccess, -100);
    lv_obj_set_y(ui_connectivityAccess, -98);
    lv_obj_set_align(ui_connectivityAccess, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connectivityAccess, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_connectivityAccess, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_connectivityAccess, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_connectivityAccess, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_connectivityAccess, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logConnectivityArea = lv_textarea_create(ui_connectivityAccess);
    lv_obj_set_width(ui_logConnectivityArea, lv_pct(100));
    lv_obj_set_flex_grow(ui_logConnectivityArea, 1);
    lv_obj_set_align(ui_logConnectivityArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_logConnectivityArea, "log...");

    ui_accessConnectivityCtn = lv_obj_create(ui_connectivityAccess);
    lv_obj_remove_style_all(ui_accessConnectivityCtn);
    lv_obj_set_width(ui_accessConnectivityCtn, lv_pct(100));
    lv_obj_set_flex_grow(ui_accessConnectivityCtn, 1);
    lv_obj_set_x(ui_accessConnectivityCtn, 343);
    lv_obj_set_y(ui_accessConnectivityCtn, -190);
    lv_obj_set_align(ui_accessConnectivityCtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_accessConnectivityCtn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_accessConnectivityCtn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_accessConnectivityCtn, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_accessConnectivityCtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_accessConnectivityCtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_accessConnectivityCtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordFieldConnectivity = lv_textarea_create(ui_accessConnectivityCtn);
    lv_obj_set_width(ui_passwordFieldConnectivity, lv_pct(100));
    lv_obj_set_height(ui_passwordFieldConnectivity, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_passwordFieldConnectivity, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passwordFieldConnectivity, "Insert the password...");
    lv_textarea_set_one_line(ui_passwordFieldConnectivity, true);
    lv_textarea_set_password_mode(ui_passwordFieldConnectivity, true);

    ui_connectBtn = lv_button_create(ui_accessConnectivityCtn);
    lv_obj_set_width(ui_connectBtn, lv_pct(50));
    lv_obj_set_height(ui_connectBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_connectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_connectBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BTN);
    ui_object_set_themeable_style_property(ui_connectBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BTN);

    ui_labelConnectBtn = lv_label_create(ui_connectBtn);
    lv_obj_set_width(ui_labelConnectBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelConnectBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelConnectBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelConnectBtn, "CONNECT");

    ui_KeyboardConnectivity = lv_keyboard_create(ui_connectivityAccess);
    lv_obj_set_width(ui_KeyboardConnectivity, lv_pct(100));
    lv_obj_set_flex_grow(ui_KeyboardConnectivity, 1);
    lv_obj_set_align(ui_KeyboardConnectivity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardConnectivity, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_wifiBtn, ui_event_wifiBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bthBtn, ui_event_bthBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scanNetButton, ui_event_scanNetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connectBtn, ui_event_connectBtn, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardConnectivity, ui_passwordFieldConnectivity);
    lv_obj_add_event_cb(ui_connectivityScreen, ui_event_connectivityScreen, LV_EVENT_ALL, NULL);

}

void ui_connectivityScreen_screen_destroy(void)
{
    if(ui_connectivityScreen) lv_obj_del(ui_connectivityScreen);

    // NULL screen variables
    ui_connectivityScreen = NULL;
    ui_Header1 = NULL;
    ui_connectivityBody = NULL;
    ui_connectivityList = NULL;
    ui_connectivitySelectorCtn = NULL;
    ui_wifiBtn = NULL;
    ui_wifiBtnLabel = NULL;
    ui_bthBtn = NULL;
    ui_bthBtnLabel = NULL;
    ui_divisorLine = NULL;
    ui_scanNetButton = NULL;
    ui_labelNetButton = NULL;
    ui_connectivityBtnContainer = NULL;
    ui_connectivityAccess = NULL;
    ui_logConnectivityArea = NULL;
    ui_accessConnectivityCtn = NULL;
    ui_passwordFieldConnectivity = NULL;
    ui_connectBtn = NULL;
    ui_labelConnectBtn = NULL;
    ui_KeyboardConnectivity = NULL;

}
