// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "../ui.h"

lv_obj_t * ui_cameraScreen = NULL;
lv_obj_t * ui_headerCameraScreen = NULL;
lv_obj_t * ui_cameraContainer = NULL;
lv_obj_t * ui_videoModeSelectorBtnContainer = NULL;
lv_obj_t * ui_loadVideoBtn = NULL;
lv_obj_t * ui_loadVideoLabel = NULL;
lv_obj_t * ui_loadCameraBtn = NULL;
lv_obj_t * ui_loadCameraLabel = NULL;
lv_obj_t * ui_panelCamera = NULL;
lv_obj_t * ui_videoDisplayer = NULL;
lv_obj_t * ui_videoCommandBtnContainer = NULL;
lv_obj_t * ui_playCameraBtn = NULL;
lv_obj_t * ui_playCameraLabel = NULL;
lv_obj_t * ui_resetCameraBtn = NULL;
lv_obj_t * ui_resetCameraLabel = NULL;
lv_obj_t * ui_recCameraBtn = NULL;
lv_obj_t * ui_recCameraLabel = NULL;
// event funtions
void ui_event_cameraScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_audioScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_audioScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_buzzerScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_buzzerScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initImgDisplayer(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        deinitCameraScreen(e);
    }
}

void ui_event_loadVideoBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loadVideo(e);
    }
}

void ui_event_loadCameraBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loadCamera(e);
    }
}

void ui_event_playCameraBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        startVideo(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        stopVideo(e);
    }
}

void ui_event_resetCameraBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resetVideo(e);
    }
}

void ui_event_recCameraBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        recVideo(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        stopRecVideo(e);
    }
}

// build funtions

void ui_cameraScreen_screen_init(void)
{
    ui_cameraScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_cameraScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_cameraScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BACKGROUND);
    ui_object_set_themeable_style_property(ui_cameraScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BACKGROUND);

    ui_headerCameraScreen = ui_Header_create(ui_cameraScreen);
    lv_obj_set_x(ui_headerCameraScreen, 0);
    lv_obj_set_y(ui_headerCameraScreen, -1);

    ui_cameraContainer = lv_obj_create(ui_cameraScreen);
    lv_obj_remove_style_all(ui_cameraContainer);
    lv_obj_set_height(ui_cameraContainer, 529);
    lv_obj_set_width(ui_cameraContainer, lv_pct(100));
    lv_obj_set_align(ui_cameraContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_cameraContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cameraContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cameraContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_cameraContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cameraContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_videoModeSelectorBtnContainer = lv_obj_create(ui_cameraContainer);
    lv_obj_remove_style_all(ui_videoModeSelectorBtnContainer);
    lv_obj_set_height(ui_videoModeSelectorBtnContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_videoModeSelectorBtnContainer, 1);
    lv_obj_set_align(ui_videoModeSelectorBtnContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_videoModeSelectorBtnContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_videoModeSelectorBtnContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_videoModeSelectorBtnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_videoModeSelectorBtnContainer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_videoModeSelectorBtnContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadVideoBtn = lv_button_create(ui_videoModeSelectorBtnContainer);
    lv_obj_set_width(ui_loadVideoBtn, lv_pct(90));
    lv_obj_set_height(ui_loadVideoBtn, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_loadVideoBtn, 19);
    lv_obj_set_y(ui_loadVideoBtn, -97);
    lv_obj_set_align(ui_loadVideoBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loadVideoBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_loadVideoBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_loadVideoBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BTN);
    ui_object_set_themeable_style_property(ui_loadVideoBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BTN);

    ui_loadVideoLabel = lv_label_create(ui_loadVideoBtn);
    lv_obj_set_width(ui_loadVideoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadVideoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loadVideoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadVideoLabel, "SELECT VIDEO");
    lv_obj_set_style_text_color(ui_loadVideoLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loadVideoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadCameraBtn = lv_button_create(ui_videoModeSelectorBtnContainer);
    lv_obj_set_width(ui_loadCameraBtn, lv_pct(90));
    lv_obj_set_height(ui_loadCameraBtn, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_loadCameraBtn, 19);
    lv_obj_set_y(ui_loadCameraBtn, -97);
    lv_obj_set_align(ui_loadCameraBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loadCameraBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_loadCameraBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_loadCameraBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BTN);
    ui_object_set_themeable_style_property(ui_loadCameraBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BTN);

    ui_loadCameraLabel = lv_label_create(ui_loadCameraBtn);
    lv_obj_set_width(ui_loadCameraLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadCameraLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loadCameraLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadCameraLabel, "OPEN CAMERA");
    lv_obj_set_style_text_color(ui_loadCameraLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loadCameraLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelCamera = lv_obj_create(ui_cameraContainer);
    lv_obj_set_width(ui_panelCamera, LV_SIZE_CONTENT);   /// 645
    lv_obj_set_height(ui_panelCamera, LV_SIZE_CONTENT);    /// 485
    lv_obj_set_x(ui_panelCamera, 0);
    lv_obj_set_y(ui_panelCamera, -10);
    lv_obj_set_align(ui_panelCamera, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelCamera, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelCamera, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelCamera, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panelCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panelCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panelCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panelCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_videoDisplayer = lv_image_create(ui_panelCamera);
    lv_obj_set_width(ui_videoDisplayer, 640);
    lv_obj_set_height(ui_videoDisplayer, 480);
    lv_obj_set_align(ui_videoDisplayer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_videoDisplayer, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_videoDisplayer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_videoCommandBtnContainer = lv_obj_create(ui_cameraContainer);
    lv_obj_remove_style_all(ui_videoCommandBtnContainer);
    lv_obj_set_height(ui_videoCommandBtnContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_videoCommandBtnContainer, 1);
    lv_obj_set_align(ui_videoCommandBtnContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_videoCommandBtnContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_videoCommandBtnContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_videoCommandBtnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_videoCommandBtnContainer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_videoCommandBtnContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playCameraBtn = lv_button_create(ui_videoCommandBtnContainer);
    lv_obj_set_width(ui_playCameraBtn, lv_pct(90));
    lv_obj_set_height(ui_playCameraBtn, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_playCameraBtn, 19);
    lv_obj_set_y(ui_playCameraBtn, -97);
    lv_obj_set_align(ui_playCameraBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_playCameraBtn, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_playCameraBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_playCameraBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playCameraBtn, lv_color_hex(0x34C759), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playCameraBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_playCameraBtn, lv_color_hex(0xFF3B30), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_playCameraBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_playCameraLabel = lv_label_create(ui_playCameraBtn);
    lv_obj_set_width(ui_playCameraLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playCameraLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playCameraLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playCameraLabel, "PLAY");
    lv_obj_set_style_text_color(ui_playCameraLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_playCameraLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resetCameraBtn = lv_button_create(ui_videoCommandBtnContainer);
    lv_obj_set_width(ui_resetCameraBtn, lv_pct(90));
    lv_obj_set_height(ui_resetCameraBtn, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_resetCameraBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_resetCameraBtn, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_resetCameraBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_resetCameraBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resetCameraBtn, lv_color_hex(0xF57305), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resetCameraBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resetCameraLabel = lv_label_create(ui_resetCameraBtn);
    lv_obj_set_width(ui_resetCameraLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resetCameraLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_resetCameraLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_resetCameraLabel, "RESET");
    lv_obj_set_style_text_color(ui_resetCameraLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_resetCameraLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_recCameraBtn = lv_button_create(ui_videoCommandBtnContainer);
    lv_obj_set_width(ui_recCameraBtn, lv_pct(90));
    lv_obj_set_height(ui_recCameraBtn, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_recCameraBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_recCameraBtn, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_recCameraBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_recCameraBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_recCameraBtn, lv_color_hex(0xA06D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_recCameraBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_recCameraBtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_recCameraBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_recCameraLabel = lv_label_create(ui_recCameraBtn);
    lv_obj_set_width(ui_recCameraLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_recCameraLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_recCameraLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_recCameraLabel, "REC");
    lv_obj_set_style_text_color(ui_recCameraLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_recCameraLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_loadVideoBtn, ui_event_loadVideoBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loadCameraBtn, ui_event_loadCameraBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_playCameraBtn, ui_event_playCameraBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_resetCameraBtn, ui_event_resetCameraBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_recCameraBtn, ui_event_recCameraBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cameraScreen, ui_event_cameraScreen, LV_EVENT_ALL, NULL);

}

void ui_cameraScreen_screen_destroy(void)
{
    if(ui_cameraScreen) lv_obj_del(ui_cameraScreen);

    // NULL screen variables
    ui_cameraScreen = NULL;
    ui_headerCameraScreen = NULL;
    ui_cameraContainer = NULL;
    ui_videoModeSelectorBtnContainer = NULL;
    ui_loadVideoBtn = NULL;
    ui_loadVideoLabel = NULL;
    ui_loadCameraBtn = NULL;
    ui_loadCameraLabel = NULL;
    ui_panelCamera = NULL;
    ui_videoDisplayer = NULL;
    ui_videoCommandBtnContainer = NULL;
    ui_playCameraBtn = NULL;
    ui_playCameraLabel = NULL;
    ui_resetCameraBtn = NULL;
    ui_resetCameraLabel = NULL;
    ui_recCameraBtn = NULL;
    ui_recCameraLabel = NULL;

}
