// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "../ui.h"

lv_obj_t * ui_canScreen = NULL;
lv_obj_t * ui_headerCanScreen = NULL;
lv_obj_t * ui_bodyCanContainer = NULL;
lv_obj_t * ui_batteryContainer = NULL;
lv_obj_t * ui_batteryArc = NULL;
lv_obj_t * ui_batteryInfoContainer = NULL;
lv_obj_t * ui_batteryTitle = NULL;
lv_obj_t * ui_batteryValue = NULL;
lv_obj_t * ui_batteryMeasureUnit = NULL;
lv_obj_t * ui_infoContainer = NULL;
lv_obj_t * ui_topLabel = NULL;
lv_obj_t * ui_imgContainer = NULL;
lv_obj_t * ui_milImg = NULL;
lv_obj_t * ui_highBeamImg = NULL;
lv_obj_t * ui_lowBeamImg = NULL;
lv_obj_t * ui_turnLeftImg = NULL;
lv_obj_t * ui_turnRightImg = NULL;
lv_obj_t * ui_cruiseImg = NULL;
lv_obj_t * ui_speedContainer = NULL;
lv_obj_t * ui_speedLabel = NULL;
lv_obj_t * ui_infoSpeedContainer = NULL;
lv_obj_t * ui_unitMeasureLabel = NULL;
lv_obj_t * ui_speedLimitImg = NULL;
lv_obj_t * ui_specificInfoContainer = NULL;
lv_obj_t * ui_tripContainer = NULL;
lv_obj_t * ui_tripLabel = NULL;
lv_obj_t * ui_trip = NULL;
lv_obj_t * ui_shiftLabel = NULL;
lv_obj_t * ui_totalContainer = NULL;
lv_obj_t * ui_totalLabel = NULL;
lv_obj_t * ui_total = NULL;
lv_obj_t * ui_energyContainer = NULL;
lv_obj_t * ui_energyArc = NULL;
lv_obj_t * ui_energyInfoContainer = NULL;
lv_obj_t * ui_energyTitle = NULL;
lv_obj_t * ui_energyValue = NULL;
lv_obj_t * ui_energyMeasureUnit = NULL;
// event funtions
void ui_event_canScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_mainCommsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_mainCommsScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_mainCommsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_mainCommsScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initCanScreen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        deinitCanScreen(e);
    }
}

// build funtions

void ui_canScreen_screen_init(void)
{
    ui_canScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_canScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_canScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BACKGROUND);
    ui_object_set_themeable_style_property(ui_canScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BACKGROUND);

    ui_headerCanScreen = ui_Header_create(ui_canScreen);
    lv_obj_set_x(ui_headerCanScreen, 0);
    lv_obj_set_y(ui_headerCanScreen, -1);

    ui_bodyCanContainer = lv_obj_create(ui_canScreen);
    lv_obj_remove_style_all(ui_bodyCanContainer);
    lv_obj_set_width(ui_bodyCanContainer, lv_pct(100));
    lv_obj_set_height(ui_bodyCanContainer, lv_pct(88));
    lv_obj_set_align(ui_bodyCanContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_bodyCanContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_bodyCanContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bodyCanContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryContainer = lv_obj_create(ui_bodyCanContainer);
    lv_obj_remove_style_all(ui_batteryContainer);
    lv_obj_set_height(ui_batteryContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_batteryContainer, 1);
    lv_obj_set_align(ui_batteryContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_batteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryArc = lv_arc_create(ui_batteryContainer);
    lv_obj_set_width(ui_batteryArc, lv_pct(112));
    lv_obj_set_height(ui_batteryArc, lv_pct(71));
    lv_obj_set_x(ui_batteryArc, -208);
    lv_obj_set_y(ui_batteryArc, -68);
    lv_obj_set_align(ui_batteryArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_batteryArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_batteryArc, 50);
    lv_arc_set_bg_angles(ui_batteryArc, 180, 0);
    lv_arc_set_mode(ui_batteryArc, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_batteryArc, 90);
    lv_obj_set_style_arc_width(ui_batteryArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_batteryArc, 350, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batteryArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_batteryInfoContainer = lv_obj_create(ui_batteryContainer);
    lv_obj_remove_style_all(ui_batteryInfoContainer);
    lv_obj_set_width(ui_batteryInfoContainer, lv_pct(100));
    lv_obj_set_height(ui_batteryInfoContainer, lv_pct(100));
    lv_obj_set_align(ui_batteryInfoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryInfoContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_batteryInfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_batteryInfoContainer,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_batteryInfoContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_batteryInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_batteryInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_batteryInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_batteryInfoContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_batteryInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryTitle = lv_label_create(ui_batteryInfoContainer);
    lv_obj_set_width(ui_batteryTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batteryTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batteryTitle, "BATTERY");
    ui_object_set_themeable_style_property(ui_batteryTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_batteryTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_align(ui_batteryTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batteryTitle, &ui_font_energyBatteryLabelFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryValue = lv_label_create(ui_batteryInfoContainer);
    lv_obj_set_width(ui_batteryValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batteryValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batteryValue, "50");
    ui_object_set_themeable_style_property(ui_batteryValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_batteryValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_batteryValue, &ui_font_energyBatteryFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryMeasureUnit = lv_label_create(ui_batteryInfoContainer);
    lv_obj_set_width(ui_batteryMeasureUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryMeasureUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batteryMeasureUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batteryMeasureUnit, "%");
    ui_object_set_themeable_style_property(ui_batteryMeasureUnit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_batteryMeasureUnit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_batteryMeasureUnit, &ui_font_energyBatteryLabelFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_infoContainer = lv_obj_create(ui_bodyCanContainer);
    lv_obj_remove_style_all(ui_infoContainer);
    lv_obj_set_height(ui_infoContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_infoContainer, 1);
    lv_obj_set_align(ui_infoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_infoContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_infoContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_infoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_infoContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_infoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topLabel = lv_label_create(ui_infoContainer);
    lv_obj_set_width(ui_topLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_topLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_topLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_topLabel, "HH:MM");
    ui_object_set_themeable_style_property(ui_topLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_topLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_topLabel, &ui_font_hmLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgContainer = lv_obj_create(ui_infoContainer);
    lv_obj_remove_style_all(ui_imgContainer);
    lv_obj_set_width(ui_imgContainer, lv_pct(100));
    lv_obj_set_height(ui_imgContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_imgContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_imgContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_imgContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_imgContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_imgContainer, -2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_milImg = lv_image_create(ui_imgContainer);
    lv_image_set_src(ui_milImg, &ui_img_mil_lamp_png);
    lv_obj_set_width(ui_milImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_milImg, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_align(ui_milImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_milImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_milImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_milImg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_highBeamImg = lv_image_create(ui_imgContainer);
    lv_image_set_src(ui_highBeamImg, &ui_img_high_beam_png);
    lv_obj_set_width(ui_highBeamImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_highBeamImg, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_align(ui_highBeamImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_highBeamImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_highBeamImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_highBeamImg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lowBeamImg = lv_image_create(ui_imgContainer);
    lv_image_set_src(ui_lowBeamImg, &ui_img_low_beam_png);
    lv_obj_set_width(ui_lowBeamImg, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_lowBeamImg, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_lowBeamImg, -1374);
    lv_obj_set_y(ui_lowBeamImg, 292);
    lv_obj_set_align(ui_lowBeamImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lowBeamImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_lowBeamImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_lowBeamImg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnLeftImg = lv_image_create(ui_imgContainer);
    lv_image_set_src(ui_turnLeftImg, &ui_img_267822735);
    lv_obj_set_width(ui_turnLeftImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_turnLeftImg, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_align(ui_turnLeftImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_turnLeftImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_turnLeftImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_turnLeftImg, 200);
    lv_obj_set_style_transform_scale(ui_turnLeftImg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnRightImg = lv_image_create(ui_imgContainer);
    lv_image_set_src(ui_turnRightImg, &ui_img_1669329308);
    lv_obj_set_width(ui_turnRightImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_turnRightImg, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_align(ui_turnRightImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_turnRightImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_turnRightImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_turnRightImg, 200);
    lv_obj_set_style_transform_scale(ui_turnRightImg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cruiseImg = lv_image_create(ui_imgContainer);
    lv_image_set_src(ui_cruiseImg, &ui_img_cruise_control_png);
    lv_obj_set_height(ui_cruiseImg, 52);
    lv_obj_set_width(ui_cruiseImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_cruiseImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cruiseImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_cruiseImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_cruiseImg, 200);
    lv_image_set_inner_align(ui_cruiseImg, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_transform_scale(ui_cruiseImg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedContainer = lv_obj_create(ui_infoContainer);
    lv_obj_remove_style_all(ui_speedContainer);
    lv_obj_set_width(ui_speedContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_speedContainer, 1);
    lv_obj_set_x(ui_speedContainer, -114);
    lv_obj_set_y(ui_speedContainer, 96);
    lv_obj_set_align(ui_speedContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_speedContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_speedContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_speedContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speedLabel = lv_label_create(ui_speedContainer);
    lv_obj_set_width(ui_speedLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_speedLabel, LV_SIZE_CONTENT);    /// 50
    lv_label_set_text(ui_speedLabel, "999");
    ui_object_set_themeable_style_property(ui_speedLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_speedLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_speedLabel, &ui_font_speedFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_infoSpeedContainer = lv_obj_create(ui_speedContainer);
    lv_obj_remove_style_all(ui_infoSpeedContainer);
    lv_obj_set_width(ui_infoSpeedContainer, lv_pct(100));
    lv_obj_set_height(ui_infoSpeedContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_infoSpeedContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_infoSpeedContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_infoSpeedContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_infoSpeedContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_unitMeasureLabel = lv_label_create(ui_infoSpeedContainer);
    lv_obj_set_height(ui_unitMeasureLabel, 50);
    lv_obj_set_flex_grow(ui_unitMeasureLabel, 1);
    lv_obj_set_align(ui_unitMeasureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unitMeasureLabel, "KM/H");
    ui_object_set_themeable_style_property(ui_unitMeasureLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_unitMeasureLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_align(ui_unitMeasureLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitMeasureLabel, &ui_font_speedLabelFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_unitMeasureLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_unitMeasureLabel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_unitMeasureLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_unitMeasureLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedLimitImg = lv_image_create(ui_infoSpeedContainer);
    lv_image_set_src(ui_speedLimitImg, &ui_img_limite_50_png);
    lv_obj_set_width(ui_speedLimitImg, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_speedLimitImg, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_speedLimitImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speedLimitImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_speedLimitImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_specificInfoContainer = lv_obj_create(ui_infoContainer);
    lv_obj_remove_style_all(ui_specificInfoContainer);
    lv_obj_set_width(ui_specificInfoContainer, lv_pct(100));
    lv_obj_set_height(ui_specificInfoContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_specificInfoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_specificInfoContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_specificInfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_specificInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_specificInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_specificInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_specificInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_specificInfoContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tripContainer = lv_obj_create(ui_specificInfoContainer);
    lv_obj_remove_style_all(ui_tripContainer);
    lv_obj_set_height(ui_tripContainer, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_flex_grow(ui_tripContainer, 1);
    lv_obj_set_align(ui_tripContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tripContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tripContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_tripContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_tripContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_tripContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tripLabel = lv_label_create(ui_tripContainer);
    lv_obj_set_width(ui_tripLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tripLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tripLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tripLabel, "TRIP");
    ui_object_set_themeable_style_property(ui_tripLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_tripLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_tripLabel, &ui_font_tripTotalLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_trip = lv_label_create(ui_tripContainer);
    lv_obj_set_width(ui_trip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_trip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_trip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_trip, "0");
    ui_object_set_themeable_style_property(ui_trip, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_trip, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_trip, &ui_font_tripTotalLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shiftLabel = lv_label_create(ui_specificInfoContainer);
    lv_obj_set_width(ui_shiftLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shiftLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_shiftLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shiftLabel, "E");
    lv_obj_set_style_text_color(ui_shiftLabel, lv_color_hex(0x16D223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shiftLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shiftLabel, &ui_font_shiftLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalContainer = lv_obj_create(ui_specificInfoContainer);
    lv_obj_remove_style_all(ui_totalContainer);
    lv_obj_set_height(ui_totalContainer, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_flex_grow(ui_totalContainer, 1);
    lv_obj_set_align(ui_totalContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_totalContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_totalContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_totalContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_totalContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_totalContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalLabel = lv_label_create(ui_totalContainer);
    lv_obj_set_width(ui_totalLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_totalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalLabel, "TOTAL");
    ui_object_set_themeable_style_property(ui_totalLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_totalLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_totalLabel, &ui_font_tripTotalLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total = lv_label_create(ui_totalContainer);
    lv_obj_set_width(ui_total, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_total, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_total, LV_ALIGN_CENTER);
    lv_label_set_text(ui_total, "0");
    ui_object_set_themeable_style_property(ui_total, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_total, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_total, &ui_font_tripTotalLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyContainer = lv_obj_create(ui_bodyCanContainer);
    lv_obj_remove_style_all(ui_energyContainer);
    lv_obj_set_height(ui_energyContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_energyContainer, 1);
    lv_obj_set_align(ui_energyContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_energyContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_energyArc = lv_arc_create(ui_energyContainer);
    lv_obj_set_width(ui_energyArc, lv_pct(112));
    lv_obj_set_height(ui_energyArc, lv_pct(71));
    lv_obj_set_x(ui_energyArc, 75);
    lv_obj_set_y(ui_energyArc, -68);
    lv_obj_set_align(ui_energyArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_energyArc, 50);
    lv_arc_set_bg_angles(ui_energyArc, 0, 180);
    lv_arc_set_rotation(ui_energyArc, 90);
    lv_obj_set_style_arc_width(ui_energyArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_energyArc, 350, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_energyArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_energyArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_energyInfoContainer = lv_obj_create(ui_energyContainer);
    lv_obj_remove_style_all(ui_energyInfoContainer);
    lv_obj_set_width(ui_energyInfoContainer, lv_pct(100));
    lv_obj_set_height(ui_energyInfoContainer, lv_pct(100));
    lv_obj_set_align(ui_energyInfoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_energyInfoContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_energyInfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_energyInfoContainer,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_energyInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_energyInfoContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_energyInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_energyInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_energyInfoContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_energyInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyTitle = lv_label_create(ui_energyInfoContainer);
    lv_obj_set_width(ui_energyTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energyTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_energyTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_energyTitle, "ENERGY");
    ui_object_set_themeable_style_property(ui_energyTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_energyTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_energyTitle, &ui_font_energyBatteryLabelFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyValue = lv_label_create(ui_energyInfoContainer);
    lv_obj_set_width(ui_energyValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energyValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_energyValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_energyValue, "999");
    ui_object_set_themeable_style_property(ui_energyValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_energyValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_energyValue, &ui_font_energyBatteryFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyMeasureUnit = lv_label_create(ui_energyInfoContainer);
    lv_obj_set_width(ui_energyMeasureUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energyMeasureUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_energyMeasureUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_energyMeasureUnit, "WH/KM");
    ui_object_set_themeable_style_property(ui_energyMeasureUnit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_energyMeasureUnit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_energyMeasureUnit, &ui_font_energyBatteryLabelFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_canScreen, ui_event_canScreen, LV_EVENT_ALL, NULL);

}

void ui_canScreen_screen_destroy(void)
{
    if(ui_canScreen) lv_obj_del(ui_canScreen);

    // NULL screen variables
    ui_canScreen = NULL;
    ui_headerCanScreen = NULL;
    ui_bodyCanContainer = NULL;
    ui_batteryContainer = NULL;
    ui_batteryArc = NULL;
    ui_batteryInfoContainer = NULL;
    ui_batteryTitle = NULL;
    ui_batteryValue = NULL;
    ui_batteryMeasureUnit = NULL;
    ui_infoContainer = NULL;
    ui_topLabel = NULL;
    ui_imgContainer = NULL;
    ui_milImg = NULL;
    ui_highBeamImg = NULL;
    ui_lowBeamImg = NULL;
    ui_turnLeftImg = NULL;
    ui_turnRightImg = NULL;
    ui_cruiseImg = NULL;
    ui_speedContainer = NULL;
    ui_speedLabel = NULL;
    ui_infoSpeedContainer = NULL;
    ui_unitMeasureLabel = NULL;
    ui_speedLimitImg = NULL;
    ui_specificInfoContainer = NULL;
    ui_tripContainer = NULL;
    ui_tripLabel = NULL;
    ui_trip = NULL;
    ui_shiftLabel = NULL;
    ui_totalContainer = NULL;
    ui_totalLabel = NULL;
    ui_total = NULL;
    ui_energyContainer = NULL;
    ui_energyArc = NULL;
    ui_energyInfoContainer = NULL;
    ui_energyTitle = NULL;
    ui_energyValue = NULL;
    ui_energyMeasureUnit = NULL;

}
