// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_CAMERASCREEN_H
#define UI_CAMERASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_cameraScreen
extern void ui_cameraScreen_screen_init(void);
extern void ui_cameraScreen_screen_destroy(void);
extern void ui_event_cameraScreen(lv_event_t * e);
extern lv_obj_t * ui_cameraScreen;
extern lv_obj_t * ui_headerCameraScreen;
extern lv_obj_t * ui_cameraContainer;
extern lv_obj_t * ui_videoLeftCard;
extern lv_obj_t * ui_videoModeSelectorLabel;
extern lv_obj_t * ui_videoModeSelectorBtnContainer;
extern void ui_event_loadVideoBtn(lv_event_t * e);
extern lv_obj_t * ui_loadVideoBtn;
extern void ui_event_loadCameraBtn(lv_event_t * e);
extern lv_obj_t * ui_loadCameraBtn;
extern lv_obj_t * ui_videoModeSelectorDescriptionCtn;
extern lv_obj_t * ui_videoModeSelectorDescriptionLabel;
extern lv_obj_t * ui_panelCamera;
extern lv_obj_t * ui_videoDisplayer;
extern lv_obj_t * ui_videoCommandBtnContainer;
extern void ui_event_playCameraBtn(lv_event_t * e);
extern lv_obj_t * ui_playCameraBtn;
extern void ui_event_resetCameraBtn(lv_event_t * e);
extern lv_obj_t * ui_resetCameraBtn;
extern void ui_event_recCameraBtn(lv_event_t * e);
extern lv_obj_t * ui_recCameraBtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

