// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_CANSCREEN_H
#define UI_CANSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_canScreen
extern void ui_canScreen_screen_init(void);
extern void ui_canScreen_screen_destroy(void);
extern void ui_event_canScreen(lv_event_t * e);
extern lv_obj_t * ui_canScreen;
extern lv_obj_t * ui_Header6;
extern lv_obj_t * ui_bodyCanContainer;
extern lv_obj_t * ui_batteryContainer;
extern lv_obj_t * ui_batteryArc;
extern lv_obj_t * ui_batteryInfoContainer;
extern lv_obj_t * ui_batteryTitle;
extern lv_obj_t * ui_batteryValue;
extern lv_obj_t * ui_batteryMeasureUnit;
extern lv_obj_t * ui_infoContainer;
extern lv_obj_t * ui_topLabel;
extern lv_obj_t * ui_imgContainer;
extern lv_obj_t * ui_milImg;
extern lv_obj_t * ui_highBeamImg;
extern lv_obj_t * ui_lowBeamImg;
extern lv_obj_t * ui_turnLeftImg;
extern lv_obj_t * ui_turnRightImg;
extern lv_obj_t * ui_cruiseImg;
extern lv_obj_t * ui_speedContainer;
extern lv_obj_t * ui_speedLabel;
extern lv_obj_t * ui_infoSpeedContainer;
extern lv_obj_t * ui_unitMeasureLabel;
extern lv_obj_t * ui_speedLimitImg;
extern lv_obj_t * ui_specificInfoContainer;
extern lv_obj_t * ui_tripContainer;
extern lv_obj_t * ui_tripLabel;
extern lv_obj_t * ui_trip;
extern lv_obj_t * ui_shiftLabel;
extern lv_obj_t * ui_totalContainer;
extern lv_obj_t * ui_totalLabel;
extern lv_obj_t * ui_total;
extern lv_obj_t * ui_energyContainer;
extern lv_obj_t * ui_energyArc;
extern lv_obj_t * ui_energyInfoContainer;
extern lv_obj_t * ui_energyTitle;
extern lv_obj_t * ui_energyValue;
extern lv_obj_t * ui_energyMeasureUnit;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

