// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_Header;
extern lv_obj_t * ui_Body;
extern lv_obj_t * ui_Connectivity;
extern lv_obj_t * ui_titleConnectivity;
extern void ui_event_btnWiFiBth(lv_event_t * e);
extern lv_obj_t * ui_btnWiFiBth;
extern lv_obj_t * ui_labelBtnWiFiBth;
extern lv_obj_t * ui_Communication;
extern lv_obj_t * ui_titleCommunication;
extern void ui_event_btnEthRs(lv_event_t * e);
extern lv_obj_t * ui_btnEthRs;
extern lv_obj_t * ui_labelBtnEthRs;
extern void ui_event_btnCan(lv_event_t * e);
extern lv_obj_t * ui_btnCan;
extern lv_obj_t * ui_labelBtnCan;
extern lv_obj_t * ui_Multimedia;
extern lv_obj_t * ui_titleMultimedia;
extern void ui_event_btnAudio(lv_event_t * e);
extern lv_obj_t * ui_btnAudio;
extern lv_obj_t * ui_labelBtnAudio;
extern void ui_event_btnCamera(lv_event_t * e);
extern lv_obj_t * ui_btnCamera;
extern lv_obj_t * ui_labelBtnCamera;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

