// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_MAINCOMMSSCREEN_H
#define UI_MAINCOMMSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainCommsScreen
extern void ui_mainCommsScreen_screen_init(void);
extern void ui_mainCommsScreen_screen_destroy(void);
extern void ui_event_mainCommsScreen(lv_event_t * e);
extern lv_obj_t * ui_mainCommsScreen;
extern lv_obj_t * ui_headerMainCommsScreen;
extern lv_obj_t * ui_miniHeaderComms;
extern void ui_event_ethBtn(lv_event_t * e);
extern lv_obj_t * ui_ethBtn;
extern lv_obj_t * ui_ehtBtnLabel;
extern void ui_event_rsBtn(lv_event_t * e);
extern lv_obj_t * ui_rsBtn;
extern lv_obj_t * ui_rsBtnLabel;
extern lv_obj_t * ui_commsTextArea;
extern lv_obj_t * ui_testCommsBtnCtn;
extern void ui_event_testCommsBtn(lv_event_t * e);
extern lv_obj_t * ui_testCommsBtn;
extern lv_obj_t * ui_testCommsBtnLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

