// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_NFCSCREEN_H
#define UI_NFCSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_nfcScreen
extern void ui_nfcScreen_screen_init(void);
extern void ui_nfcScreen_screen_destroy(void);
extern void ui_event_nfcScreen(lv_event_t * e);
extern lv_obj_t * ui_nfcScreen;
extern lv_obj_t * ui_headerNfcScreen;
extern lv_obj_t * ui_nfcTitleLabel;
extern lv_obj_t * ui_nfcLed;
extern lv_obj_t * ui_nfcTextArea;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

