// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "../ui.h"

lv_obj_t * ui_nfcScreen = NULL;
lv_obj_t * ui_headerNfcScreen = NULL;
lv_obj_t * ui_nfcTitleLabel = NULL;
lv_obj_t * ui_nfcLed = NULL;
lv_obj_t * ui_nfcTextArea = NULL;
// event funtions
void ui_event_nfcScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initNfcScreen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        deinitNfcScreen(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_connectivityScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_connectivityScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_connectivityScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_connectivityScreen_screen_init);
    }
}

// build funtions

void ui_nfcScreen_screen_init(void)
{
    ui_nfcScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_nfcScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_nfcScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_nfcScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_nfcScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BACKGROUND);
    ui_object_set_themeable_style_property(ui_nfcScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BACKGROUND);

    ui_headerNfcScreen = ui_Header_create(ui_nfcScreen);
    lv_obj_set_x(ui_headerNfcScreen, 0);
    lv_obj_set_y(ui_headerNfcScreen, -1);

    ui_nfcTitleLabel = lv_label_create(ui_nfcScreen);
    lv_obj_set_width(ui_nfcTitleLabel, lv_pct(60));
    lv_obj_set_height(ui_nfcTitleLabel, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_nfcTitleLabel, -316);
    lv_obj_set_y(ui_nfcTitleLabel, -281);
    lv_obj_set_align(ui_nfcTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nfcTitleLabel, "NFC");
    ui_object_set_themeable_style_property(ui_nfcTitleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_nfcTitleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_align(ui_nfcTitleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_nfcTitleLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nfcTitleLabel, &ui_font_energyBatteryFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_nfcTitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_nfcTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_nfcTitleLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nfcTitleLabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nfcLed = lv_obj_create(ui_nfcScreen);
    lv_obj_set_width(ui_nfcLed, 150);
    lv_obj_set_height(ui_nfcLed, 150);
    lv_obj_set_align(ui_nfcLed, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nfcLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_nfcLed, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nfcLed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nfcLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nfcLed, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_nfcLed, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_nfcTextArea = lv_textarea_create(ui_nfcScreen);
    lv_obj_set_width(ui_nfcTextArea, lv_pct(88));
    lv_obj_set_height(ui_nfcTextArea, lv_pct(33));
    lv_obj_set_x(ui_nfcTextArea, -109);
    lv_obj_set_y(ui_nfcTextArea, 226);
    lv_obj_set_align(ui_nfcTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_nfcTextArea, "Qui verranno visualizzati i dispositivi connessi...");
    lv_obj_remove_flag(ui_nfcTextArea, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_nfcScreen, ui_event_nfcScreen, LV_EVENT_ALL, NULL);

}

void ui_nfcScreen_screen_destroy(void)
{
    if(ui_nfcScreen) lv_obj_del(ui_nfcScreen);

    // NULL screen variables
    ui_nfcScreen = NULL;
    ui_headerNfcScreen = NULL;
    ui_nfcTitleLabel = NULL;
    ui_nfcLed = NULL;
    ui_nfcTextArea = NULL;

}
