// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "../ui.h"

lv_obj_t * ui_startScreen = NULL;
lv_obj_t * ui_startTitle = NULL;
lv_obj_t * ui_testInterfacesButton = NULL;
lv_obj_t * ui_testInterfacesBtnLabel = NULL;
// event funtions
void ui_event_testInterfacesButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}

// build funtions

void ui_startScreen_screen_init(void)
{
    ui_startScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_startScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_startScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_startScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_startScreen, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_startScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_startScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_startScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_startScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_startScreen, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_startScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startTitle = lv_label_create(ui_startScreen);
    lv_obj_set_width(ui_startTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_startTitle, 0);
    lv_obj_set_y(ui_startTitle, lv_pct(20));
    lv_obj_set_align(ui_startTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_startTitle, "SOM LITE DEMO");
    lv_obj_set_style_text_color(ui_startTitle, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_startTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_startTitle, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_startTitle, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_startTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_startTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_startTitle, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_startTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testInterfacesButton = lv_button_create(ui_startScreen);
    lv_obj_set_width(ui_testInterfacesButton, lv_pct(35));
    lv_obj_set_height(ui_testInterfacesButton, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_testInterfacesButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testInterfacesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testInterfacesButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_testInterfacesButton, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_testInterfacesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testInterfacesBtnLabel = lv_label_create(ui_testInterfacesButton);
    lv_obj_set_width(ui_testInterfacesBtnLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_testInterfacesBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_testInterfacesBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_testInterfacesBtnLabel, "TEST INTERFACES");
    lv_obj_set_style_text_color(ui_testInterfacesBtnLabel, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_testInterfacesBtnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_testInterfacesBtnLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_testInterfacesButton, ui_event_testInterfacesButton, LV_EVENT_ALL, NULL);

}

void ui_startScreen_screen_destroy(void)
{
    if(ui_startScreen) lv_obj_del(ui_startScreen);

    // NULL screen variables
    ui_startScreen = NULL;
    ui_startTitle = NULL;
    ui_testInterfacesButton = NULL;
    ui_testInterfacesBtnLabel = NULL;

}
