// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef UI_STARTSCREEN_H
#define UI_STARTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_startScreen
extern void ui_startScreen_screen_init(void);
extern void ui_startScreen_screen_destroy(void);
extern lv_obj_t * ui_startScreen;
extern lv_obj_t * ui_startTitle;
extern void ui_event_testInterfacesButton(lv_event_t * e);
extern lv_obj_t * ui_testInterfacesButton;
extern lv_obj_t * ui_testInterfacesBtnLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

