// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef _UIDEMO_UI_H
#define _UIDEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_mainScreen.h"
#include "screens/ui_audioScreen.h"
#include "screens/ui_cameraScreen.h"
#include "screens/ui_connectivityScreen.h"
#include "screens/ui_mainCommsScreen.h"
#include "screens/ui_canScreen.h"
#include "screens/ui_buzzerScreen.h"
#include "screens/ui_nfcScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_homeicon_png);    // assets/homeIcon.png
LV_IMG_DECLARE(ui_img_mic_no_rec_png);    // assets/mic_no_rec.png
LV_IMG_DECLARE(ui_img_no_audio_png);    // assets/no_audio.png
LV_IMG_DECLARE(ui_img_audio_png);    // assets/audio.png
LV_IMG_DECLARE(ui_img_add_file_white_png);    // assets/add_file_white.png
LV_IMG_DECLARE(ui_img_play_white_png);    // assets/play_white.png
LV_IMG_DECLARE(ui_img_pause_white_png);    // assets/pause_white.png
LV_IMG_DECLARE(ui_img_reset_audio_png);    // assets/reset_audio.png
LV_IMG_DECLARE(ui_img_volume_down_png);    // assets/volume_down.png
LV_IMG_DECLARE(ui_img_volume_up_png);    // assets/volume_up.png
LV_IMG_DECLARE(ui_img_wifi_blue_png);    // assets/wifi_blue.png
LV_IMG_DECLARE(ui_img_wifi_white_png);    // assets/wifi_white.png
LV_IMG_DECLARE(ui_img_bth_blue_png);    // assets/bth_blue.png
LV_IMG_DECLARE(ui_img_bth_white_png);    // assets/bth_white.png
LV_IMG_DECLARE(ui_img_restart_scan_png);    // assets/restart_scan.png
LV_IMG_DECLARE(ui_img_mil_lamp_png);    // assets/MIL_lamp.png
LV_IMG_DECLARE(ui_img_high_beam_png);    // assets/high_beam.png
LV_IMG_DECLARE(ui_img_low_beam_png);    // assets/low_beam.png
LV_IMG_DECLARE(ui_img_267822735);    // assets/left_arrow (2).png
LV_IMG_DECLARE(ui_img_1669329308);    // assets/right_arrow (2).png
LV_IMG_DECLARE(ui_img_cruise_control_png);    // assets/cruise_control.png
LV_IMG_DECLARE(ui_img_limite_50_png);    // assets/limite_50.png
LV_IMG_DECLARE(ui_img_bell_png);    // assets/bell.png
LV_IMG_DECLARE(ui_img_ringing_bell_png);    // assets/ringing_bell.png
LV_IMG_DECLARE(ui_img_nfc_logo_png);    // assets/nfc_logo.png
LV_IMG_DECLARE(ui_img_nfc_wait_png);    // assets/nfc_wait.png
LV_IMG_DECLARE(ui_img_nfc_ok_png);    // assets/nfc_ok.png

// FONTS
LV_FONT_DECLARE(ui_font_energyBatteryFont);
LV_FONT_DECLARE(ui_font_energyBatteryLabelFont);
LV_FONT_DECLARE(ui_font_hmLabel);
LV_FONT_DECLARE(ui_font_shiftLabel);
LV_FONT_DECLARE(ui_font_speedFont);
LV_FONT_DECLARE(ui_font_speedLabelFont);
LV_FONT_DECLARE(ui_font_tripTotalLabel);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
