// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void deinitAudioScreen(lv_event_t * e);
void initAudioScreen(lv_event_t * e);
void recordAudio(lv_event_t * e);
void stopRecordAudio(lv_event_t * e);
void selectFileAudio(lv_event_t * e);
void playFileAudio(lv_event_t * e);
void stopFileAudio(lv_event_t * e);
void resetFileAudio(lv_event_t * e);
void changeVolume(lv_event_t * e);
void initImgDisplayer(lv_event_t * e);
void deinitCameraScreen(lv_event_t * e);
void loadVideo(lv_event_t * e);
void loadCamera(lv_event_t * e);
void startVideo(lv_event_t * e);
void stopVideo(lv_event_t * e);
void resetVideo(lv_event_t * e);
void recVideo(lv_event_t * e);
void stopRecVideo(lv_event_t * e);
void initConnectivityScreen(lv_event_t * e);
void deinitConnectivityScreen(lv_event_t * e);
void deinitWifiMode(lv_event_t * e);
void initWifiMode(lv_event_t * e);
void initBthMode(lv_event_t * e);
void deinitBthMode(lv_event_t * e);
void scanNetwork(lv_event_t * e);
void connectDisconnectSelected(lv_event_t * e);
void initCommsScreen(lv_event_t * e);
void deinitCommsScreen(lv_event_t * e);
void initEthernetMode(lv_event_t * e);
void deinitEthernetMode(lv_event_t * e);
void initRsMode(lv_event_t * e);
void deinitRsMode(lv_event_t * e);
void sendTestMessageComms(lv_event_t * e);
void initCanScreen(lv_event_t * e);
void deinitCanScreen(lv_event_t * e);
void initBuzzerScreen(lv_event_t * e);
void deinitBuzzerScreen(lv_event_t * e);
void btnBuzzerClkHandler(lv_event_t * e);
void initNfcScreen(lv_event_t * e);
void deinitNfcScreen(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
