// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "ui.h"
#include "../logic/media/mediaLogic.h"
#include "../logic/connectivity/connectivityLogic.h"
#include "../logic/communications/communicationsLogic.h"

/*
======================================== 
    MULTIMEDIA (AUDIO / CAMERA / BUZZER)
========================================
*/
/*
-------------------------------------
    AUDIO
-------------------------------------
*/

void recordAudio(lv_event_t * e)
{
	// Your code here
	logic_record_audio();
	
}

void stopRecordAudio(lv_event_t * e)
{
	// Your code here
	logic_stop_record_audio();
}

void changeVolume(lv_event_t * e)
{
	// Your code here
	logic_change_volume();
}

void selectFileAudio(lv_event_t * e)
{
	// Your code here
	logic_select_file_audio();
}

void playFileAudio(lv_event_t * e)
{
	// Your code here
	logic_play_file_audio();
}

void stopFileAudio(lv_event_t * e)
{
	// Your code here
	logic_stop_file_audio();
}

void resetFileAudio(lv_event_t * e)
{
	// Your code here
	logic_reset_file_audio();
}

void deinitAudioScreen(lv_event_t * e)
{
	// Your code here
	logic_deinit_audio_screen();
}

void initAudioScreen(lv_event_t * e)
{
	// Your code here
	logic_init_audio_screen();
}

/*
-------------------------------------
    CAMERA
-------------------------------------
*/
void startVideo(lv_event_t * e)
{
	// Your code here
	logic_start_video();
}

void stopVideo(lv_event_t * e)
{
	// Your code here
	logic_stop_video();
}

void initImgDisplayer(lv_event_t * e)
{
	// Your code here
	createImgDisplayer();
}

void resetVideo(lv_event_t * e)
{
	// Your code here
	logic_reset_video();
}

void loadVideo(lv_event_t * e)
{
	// Your code here
	logic_load_video();
}

void loadCamera(lv_event_t * e)
{
	// Your code here
	logic_load_camera();
}

void deinitCameraScreen(lv_event_t * e)
{
	// Your code here
	logic_deinit_camera_screen();
}

void recVideo(lv_event_t * e)
{
	// Your code here
	logic_rec_video();
}

void stopRecVideo(lv_event_t * e)
{
	// Your code here
	logic_stop_rec_video();
}

/*
-------------------------------------
	BUZZER
-------------------------------------
*/

void initBuzzerScreen(lv_event_t * e)
{
	// Your code here
	logic_init_buzzer_screen();
}

void deinitBuzzerScreen(lv_event_t * e)
{
	// Your code here
	logic_deinit_buzzer_screen();
}

void btnBuzzerClkHandler(lv_event_t * e)
{
	// Your code here
	logic_btn_buzzer_click_handler();
}


/*
=====================================
    CONNECTIVITY (WIFI/BTH)
=====================================
*/

/*
-------------------------------------
	GENERAL
-------------------------------------
*/

void initConnectivityScreen(lv_event_t * e)
{
	// Your code here
	logic_init_connectivity_screen();
}

void deinitConnectivityScreen(lv_event_t * e)
{
	// Your code here
	logic_deinit_connectivity_screen();
}

void connectDisconnectSelected(lv_event_t * e)
{
	// Your code here
	logic_connect_disconnect_selected();
}

void scanNetwork(lv_event_t * e)
{
	// Your code here
	logic_scan_network();
}

/*
-------------------------------------
	WIFI
-------------------------------------
*/

void initWifiMode(lv_event_t * e)
{
	// Your code here
	setConnectionMode(WIFI_MODE);
}

void deinitWifiMode(lv_event_t * e)
{
	// Your code here
	setConnectionMode(NONE_CONNECTIVITY_MODE);
}

/*
-------------------------------------
	BLUETOOTH
-------------------------------------
*/

void initBthMode(lv_event_t * e)
{
	// Your code here
	setConnectionMode(BTH_MODE);
}

void deinitBthMode(lv_event_t * e)
{
	// Your code here
	setConnectionMode(NONE_CONNECTIVITY_MODE);
}



/*
========================================
    COMMUNICATIONS (ETH/RS-485/CAN)
========================================
*/

/*
-------------------------------------
	GENERAL
-------------------------------------
*/

void initCommsScreen(lv_event_t * e)
{
	// Your code here
	logic_init_communication_screen();
}

void deinitCommsScreen(lv_event_t * e)
{
	// Your code here
	logic_deinit_communication_screen();
}

void sendTestMessageComms(lv_event_t * e)
{
	// Your code here
	logic_send_test_message_comms();
}


/*
-------------------------------------
	ETHERNET
-------------------------------------
*/

void initEthernetMode(lv_event_t * e)
{
	// Your code here
	setCommunicationMode(ETH_MODE);
}

void deinitEthernetMode(lv_event_t * e)
{
	// Your code here
	setCommunicationMode(NONE_COMMUNICATION_MODE);
}

/*
-------------------------------------
	RS-485
-------------------------------------
*/

void initRsMode(lv_event_t * e)
{
	// Your code here
	setCommunicationMode(RS_MODE);
}

void deinitRsMode(lv_event_t * e)
{
	// Your code here
	setCommunicationMode(NONE_COMMUNICATION_MODE);
}

/*
-------------------------------------
	CAN
-------------------------------------
*/

void initCanScreen(lv_event_t * e)
{
	// Your code here
	logic_init_can_mode();
}

void deinitCanScreen(lv_event_t * e)
{
	// Your code here
	logic_deinit_can_mode();
}
