// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: uiDEMO

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_BACKGROUND[1] = {0x333333};
const ui_theme_variable_t _ui_theme_alpha_BACKGROUND[1] = {255};

const ui_theme_variable_t _ui_theme_color_HEADER[1] = {0x14191E};
const ui_theme_variable_t _ui_theme_alpha_HEADER[1] = {255};

const ui_theme_variable_t _ui_theme_color_TEXT[1] = {0xEDEDED};
const ui_theme_variable_t _ui_theme_alpha_TEXT[1] = {255};

const ui_theme_variable_t _ui_theme_color_MAINBTN[1] = {0x242B33};
const ui_theme_variable_t _ui_theme_alpha_MAINBTN[1] = {255};

const ui_theme_variable_t _ui_theme_color_BTN[1] = {0x1F3A6D};
const ui_theme_variable_t _ui_theme_alpha_BTN[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

